### ISSUE TITLE
go get v2 error : v2がgo getできない

### ISSUE THREAD

**Issue by ddddddO** [nokute78/go-bit#12]
Goでv2以降にすると、go.modファイルを書き換える必要があるそうです。
- https://christina04.hatenablog.com/entry/go-modules-major-version
- https://blog.golang.org/v2-go-modules

こちらのパッケージのv2をちょっと触ってみたいので、対応いただければお願いしたいですm(__)m

**Comment by nokute78** [comment]
ご指摘ありがとうございます。確認します。

====
go.mod should be rewrite to support v2.

* https://christina04.hatenablog.com/entry/go-modules-major-version
* https://blog.golang.org/v2-go-modules

**Comment by nokute78** [comment]
@ddddddO 対応してみました。v2.2.1としてリリース済みです。ご確認いただけますでしょうか。

https://github.com/nokute78/go-bit#usage
に記載のコードをtcp.goとして保存し、下記のDockerfileでtcp.goが走ることを確認しました。

```
FROM golang:1.17

WORKDIR /
ADD tcp.go /

RUN go mod init sample
RUN go mod tidy
CMD ["go", "run", "/tcp.go"]
```

=====

I released v2.2.1 to support v2 directory.

https://github.com/nokute78/go-bit#usage
I tested usage example code (saved as tcp.go) using below Dockerfile.

```
FROM golang:1.17

WORKDIR /
ADD tcp.go /

RUN go mod init sample
RUN go mod tidy
CMD ["go", "run", "/tcp.go"]
```

**Comment by ddddddO** [comment]
ご対応ありがとうございます！こちらでも動作することを確認できました！

コードは、https://github.com/nokute78/go-bit#usage を使わせていただき、
`go mod init` , `go mod tidy` で v2.2.1 のインストールを確認

```
module github.com/ddddddO/work/go/bit/thirdparty

go 1.17

require github.com/nokute78/go-bit/v2 v2.2.1

require github.com/goccy/go-reflect v1.1.0 // indirect

```

`go run main.go` で以下出力を確認

```
src=55397 dst=443
SeqNo=1273001677 AckNo=1221095567
HeaderLen(raw)=[1 0 1 0]
Ack=true
```

お手数をおかけしましたm(__)m
使わせてもらいます！

**Comment by nokute78** [comment]
ご確認いただき、ありがとうございます。無事動作したようで、良かったです。
それでは、issueをクローズさせていただきます。

====
Thank you for testing.
The issue is fixed by #13, so I close this issue.
